# Exploratory Data Analysis (EDA)
#### https://www.analyticsvidhya.com/blog/2021/05/exploratory-data-analysis-eda-a-step-by-step-guide/

## Importing libraries

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

## Reading data

In [40]:
# Load the RAW_2019-2020 NSCH_Topical_CAHMI_DRC.csv dataset.
file_path = ('C:/Users/tligh/Desktop/Sensory_Needs_Occupational_Therapy/Data/2019-2020 NSCH_Topical_CAHMI_DRC_Original.csv')
Original_NCSH_df = pd.read_csv(file_path)
Original_NCSH_df.head(10)

,FIPSST,STRATUM,HHID,FORMTYPE,TOTKIDS_R,TENURE,HHLANGUAGE,SC_AGE_YEARS,SC_SEX,K2Q35A_1_YEARS,...,npm9bullied_1920,npm9bully_1920,npm10PrVi_1920,npm11MHCSHCN_1920,npm11MHnonCSHCN_1920,npm12TransCSHCN_1920,npm12TransNonCSHCN_1920,npm13_2DePrev_1920,npm14_2Smoke_1920,npm15AdIns_1920
0,1,1,19000167,3,2,3,1,17,1,95,...,1,1,2,95,1,95,2,1,2,1
1,1,1,19001238,1,4,1,1,4,2,95,...,90,90,95,95,1,90,90,1,2,1
2,1,1,19001344,3,3,1,1,14,1,95,...,2,1,1,95,1,95,2,1,2,2
3,1,1,19001345,3,1,1,1,16,2,95,...,2,1,1,95,1,95,1,1,2,2
4,1,1,19001347,1,1,3,1,5,2,95,...,90,90,95,2,95,90,90,1,2,1
5,1,1,19001355,1,1,1,1,4,2,95,...,90,90,95,95,2,90,90,2,2,1
6,1,1,19001524,1,1,1,1,4,1,95,...,90,90,95,95,2,90,90,1,2,1
7,1,1,19001651,3,2,1,1,13,1,95,...,1,1,1,95,2,95,2,1,1,1
8,1,1,19001670,3,2,1,1,13,1,95,...,1,1,1,95,1,95,2,1,2,1
9,1,1,19001714,3,1,2,1,15,1,95,...,2,2,1,95,1,95,2,1,2,1

K2Q35A Question: Has a doctor or other health care provider EVER told you that this child hasâ€¦ Autism or Autism Spectrum Disorder (ASD)? Include diagnoses of Aspergerâ€™â€™s Disorder or Pervasive Developmental Disorder (PDD).

K2Q35B Question: If yes, does this child CURRENTLY have the condition? (variable name differs based on condition)

In [34]:
Autism_types_df = pd.DataFrame.columns(Original_NCSH_df)
Autism_types_df.head()

TypeError: 'pandas._libs.properties.AxisProperty' object is not callable

In [42]:
Autism_types_df = pd.DataFrame(Original_NCSH_df).columns ([(Original_NCSH_df)])
Autism_types_df.head()

TypeError: 'Index' object is not callable

In [39]:
# Check to see if how Autims types compare, are they mutulaly exclusive?
df_cols = ['K2Q35A', 'month' , 'year', 'min_temp', 'max_temp']

Autism_type_df = Original_NCSH_df
Autism_type_df = pd.DataFrame(columns=['FIPSST'], values)
Autism_type_df.head()

SyntaxError: positional argument follows keyword argument (3892255584.py, line 5)

### Descriptive Statistics

In [26]:
Original_NCSH_df.describe(include='all')

,FIPSST,STRATUM,HHID,FORMTYPE,TOTKIDS_R,TENURE,HHLANGUAGE,SC_AGE_YEARS,SC_SEX,K2Q35A_1_YEARS,...,npm9bullied_1920,npm9bully_1920,npm10PrVi_1920,npm11MHCSHCN_1920,npm11MHnonCSHCN_1920,npm12TransCSHCN_1920,npm12TransNonCSHCN_1920,npm13_2DePrev_1920,npm14_2Smoke_1920,npm15AdIns_1920
count,72210.000000,72210.000000,7.221000e+04,72210.000000,72210.000000,72210.000000,72210.000000,72210.000000,72210.000000,72210.000000,...,72210.000000,72210.000000,72210.000000,72210.000000,72210.000000,72210.000000,72210.000000,72210.000000,72210.000000,72210.000000
mean,29.328930,1.076347,1.970175e+07,2.130924,1.846503,1.485985,1.500914,9.469035,1.481692,92.586913,...,55.652943,55.552181,56.542376,72.927157,23.648387,80.545201,65.342155,4.714499,3.942487,1.714901
std,15.799924,0.265554,5.090231e+05,0.822470,0.865593,0.813208,6.236203,5.182155,0.499668,14.627575,...,44.872026,44.987500,46.136246,39.701319,39.802355,29.662618,40.328840,17.919338,14.059754,6.098872
min,1.000000,1.000000,1.900000e+07,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,16.000000,1.000000,1.911378e+07,1.000000,1.000000,1.000000,1.000000,5.000000,1.000000,95.000000,...,1.000000,1.000000,1.000000,95.000000,1.000000,90.000000,2.000000,1.000000,2.000000,1.000000
50%,30.000000,1.000000,2.003801e+07,2.000000,2.000000,1.000000,1.000000,10.000000,1.000000,95.000000,...,90.000000,90.000000,95.000000,95.000000,2.000000,90.000000,90.000000,1.000000,2.000000,1.000000
75%,41.000000,1.000000,2.014001e+07,3.000000,2.000000,2.000000,1.000000,14.000000,2.000000,95.000000,...,95.000000,95.000000,95.000000,95.000000,2.000000,95.000000,90.000000,1.000000,2.000000,2.000000
max,56.000000,2.000000,2.024000e+07,3.000000,4.000000,4.000000,99.000000,17.000000,2.000000,99.000000,...,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000

### Missing value imputation

In [25]:
Original_NCSH_df.isnull().sum()

FIPSST                     0
STRATUM                    0
HHID                       0
FORMTYPE                   0
TOTKIDS_R                  0
                          ..
npm12TransCSHCN_1920       0
npm12TransNonCSHCN_1920    0
npm13_2DePrev_1920         0
npm14_2Smoke_1920          0
npm15AdIns_1920            0
Length: 820, dtype: int64

## Graphical representation

####  Univariate Analysis - Bar Chart

In [ ]:
plt.subplot(221)

df['gender'].value_counts().plot(kind='bar', title='Gender of students', figsize=(16,9))

plt.xticks(rotation=0)

plt.subplot(222)

df['race/ethnicity'].value_counts().plot(kind='bar', title='Race/ethnicity of students')

plt.xticks(rotation=0)

plt.subplot(223)

df['lunch'].value_counts().plot(kind='bar', title='Lunch status of students')

plt.xticks(rotation=0)

plt.subplot(224)

df['test preparation course'].value_counts().plot(kind='bar', title='Test preparation course')

plt.xticks(rotation=0)

plt.show()

####  Univariate Analysis - Box Plot

####  Univariate Analysis - Distribution Plot

####  Univariate Analysis: Coorelation - Heatmap

#### Bivariate Analysis - Relational Plot

#### Bivariate Analysis -Line Plot

#### Bivariate Analysis -Horizontal Bar Graph